# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bb8dec8612bc856550e107be928201626debee3a06b3ff26fbf43d91d9a02eeb99dcfc5e6555d68334f9e79f62ead2932cee7968263c646b59b97c91b7c71e5

test:
  secret_key_base: 6542a0e5cdfbad4e895ff75d59665959c0c9c4053bc9a174fb1070450c20a41ef5fb08b98848d6e2f0d1f6e758d71265f890454f43ef9147073cdc53bf1d6dbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
